# Site settings
title: ~jmrepetti
email: "jmrepetti@gmail.com"
twitter: "https://twitter.com/jmrepetti"
instagram: "https://instagram.com/jmrepetti"
github: "https://github.com/jmrepetti"
description: "Personal blog about programming, music and everything."
baseurl: ""


collections:
- articles
- howtos

    
# Build settings
markdown: redcarpet
pygments: true
permalink: date
